#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Aug 28 05:13:03 UTC 2026
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1787893983400
maven-metadata-central.xml.lastUpdated=1787893983352
maven-metadata-sonatype-nexus-snapshots.xml.error=
